// YouTube caption extraction, shared by /api/video (serverless) and
// scripts/yt-note.mjs (local CLI). Underscore prefix keeps Vercel from routing
// this file as a function.
//
// We read the video's caption track (manual or auto-generated) through
// InnerTube instead of downloading audio: captions are just text, so this needs
// no yt-dlp and no Whisper, and fits in a short function invocation.
//
// IMPORTANT — where this runs matters. YouTube answers InnerTube requests from
// datacenter IPs (Vercel included) with "Sign in to confirm you're not a bot",
// so the serverless path fails for most videos. From a normal home connection
// the same code works. That is why scripts/yt-note.mjs exists: it reuses this
// module on your own machine and posts the result to /api/add.

// Public InnerTube key (the constant every YouTube web client ships with).
const INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"

// Mobile app clients. We ask as the ANDROID/IOS app because, since 2024, the
// caption URLs from the *web* watch page return an empty body without a
// BotGuard "pot" token — the mobile clients still serve caption text directly.
//
// Only these two are left. ANDROID_VR, TVHTML5(_SIMPLY_EMBEDDED_PLAYER) and
// WEB_EMBEDDED_PLAYER used to be here as bot-gate dodges; as of 2026 they fail
// for everyone — LOGIN_REQUIRED, "YouTube is no longer supported in this
// application or device", "This video is unavailable" — even from a residential
// IP, and bumping their clientVersion does not revive them. Keeping them only
// slowed every request down and, worse, their errors masked the real reason in
// getCaptions()'s diagnosis. Verify with a real request before adding one back.
const CLIENTS = [
  {
    name: "IOS",
    ua: "com.google.ios.youtube/20.29.6 (iPhone16,2; U; CPU iOS 18_5 like Mac OS X)",
    context: {
      clientName: "IOS",
      clientVersion: "20.29.6",
      deviceMake: "Apple",
      deviceModel: "iPhone16,2",
      osName: "iPhone",
      osVersion: "18.5.0.22F76",
      hl: "en",
    },
  },
  {
    name: "ANDROID",
    ua: "com.google.android.youtube/20.29.38 (Linux; U; Android 14) gzip",
    context: {
      clientName: "ANDROID",
      clientVersion: "20.29.38",
      androidSdkVersion: 34,
      osName: "Android",
      osVersion: "14",
      hl: "en",
    },
  },
]

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

// How the caller should recover when YouTube refuses a server-side request.
export const BOT_GATE_HINT =
  "YouTube가 서버 요청을 봇으로 차단했습니다 (Sign in to confirm you're not a bot). " +
  "이 링크는 내 컴퓨터에서 `node scripts/yt-note.mjs <링크>` 로 만들거나, " +
  "영상 페이지의 “...더보기 → 스크립트 표시” 자막을 복사해 ‘노트 작성’ 탭에 붙여넣어 주세요."

// Pull the 11-char video id out of any common YouTube URL shape.
export function videoId(url) {
  try {
    const u = new URL(String(url).trim())
    const host = u.hostname.replace(/^www\./, "")
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || null
    if (host.endsWith("youtube.com")) {
      if (u.searchParams.get("v")) return u.searchParams.get("v")
      const m = u.pathname.match(/\/(?:shorts|embed|live|v)\/([^/?#]+)/)
      if (m) return m[1]
    }
  } catch {
    /* not a URL — fall through to a loose match */
  }
  const m = String(url).match(/[a-zA-Z0-9_-]{11}/)
  return m ? m[0] : null
}

async function playerFor(client, id) {
  const r = await fetch(`https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "User-Agent": client.ua },
    body: JSON.stringify({ context: { client: client.context }, videoId: id }),
  })
  if (!r.ok) return null
  return r.json().catch(() => null)
}

// Try each client until one both passes the bot gate AND serves non-empty
// caption text. Returns { title, cues, language, autoGenerated, description,
// durationMs } on success, or { error, status } describing why all clients failed.
export async function getCaptions(id) {
  let title = ""
  let description = ""
  let durationMs = 0
  let sawBotGate = false
  let sawNoCaptions = false
  let sawUnplayable = ""

  for (const c of CLIENTS) {
    let pr
    try {
      pr = await playerFor(c, id)
    } catch {
      continue
    }
    if (!pr) continue

    if (pr.videoDetails?.title) title = pr.videoDetails.title
    if (pr.videoDetails?.shortDescription) description = pr.videoDetails.shortDescription
    if (pr.videoDetails?.lengthSeconds) durationMs = parseInt(pr.videoDetails.lengthSeconds, 10) * 1000
    const status = pr.playabilityStatus?.status
    const reason = pr.playabilityStatus?.reason || pr.playabilityStatus?.errorScreen || ""

    if (status && status !== "OK") {
      if (/not a bot|sign in|LOGIN_REQUIRED/i.test(status + " " + reason)) sawBotGate = true
      else sawUnplayable = typeof reason === "string" && reason ? reason : status
      continue // this client is blocked — try the next
    }

    const tracks = pr.captions?.playerCaptionsTracklistRenderer?.captionTracks || []
    if (!tracks.length) {
      sawNoCaptions = true
      continue
    }

    const track = pickTrack(tracks)
    let cues = []
    try {
      cues = await fetchCaptionCues(track.baseUrl)
    } catch {
      cues = []
    }
    if (cues.length) {
      return {
        title: title || `YouTube ${id}`,
        cues,
        description,
        durationMs,
        language: track.languageCode || "",
        autoGenerated: track.kind === "asr",
      }
    }
    // tracks present but body empty (datacenter-blocked caption host) → next client
  }

  // Nothing worked — report the most actionable reason we saw. The bot gate is
  // checked FIRST: when it fires, any "unplayable" text we also collected came
  // from a client YouTube had already refused, so it describes that client, not
  // the video. Reporting it instead would send you chasing a phantom problem.
  if (sawBotGate) {
    return { error: BOT_GATE_HINT, status: 502, botGate: true }
  }
  if (sawNoCaptions) {
    return {
      error: "이 영상에는 자막이 없어 노트를 만들 수 없습니다. 자막(자동 생성 포함)이 있는 영상을 사용하세요.",
      status: 422,
    }
  }
  if (sawUnplayable) {
    return { error: `재생할 수 없는 영상입니다: ${sawUnplayable}`, status: 422 }
  }
  return { error: "영상 정보를 읽지 못했습니다. 잠시 후 다시 시도하세요.", status: 502 }
}

// Prefer a human (non-ASR) track; within that, prefer Korean/English; else take
// whatever exists (the note step translates to English anyway).
function pickTrack(tracks) {
  const score = (t) => {
    let s = 0
    if (t.kind !== "asr") s += 4 // manual captions beat auto-generated
    const lang = (t.languageCode || "").toLowerCase()
    if (lang.startsWith("ko")) s += 2
    else if (lang.startsWith("en")) s += 1
    return s
  }
  return [...tracks].sort((a, b) => score(b) - score(a))[0]
}

function decodeEntities(s) {
  return s
    .replace(/&#39;|&#039;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
}

const clean = (s) => decodeEntities(String(s).replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ").trim()

// Fetch the caption track as TIMED cues [{ tMs, text }] so we can slice it into
// chapters later. Mobile clients return either json3 ({events:[{tStartMs,segs}]})
// or timedtext XML (<p t="ms">…</p> for fmt=3, or <text start="sec">… for legacy).
async function fetchCaptionCues(baseUrl) {
  const url = baseUrl + (baseUrl.includes("?") ? "&" : "?") + "fmt=json3"
  const r = await fetch(url, { headers: { "User-Agent": UA, "Accept-Language": "en" } })
  if (!r.ok) return []
  const raw = (await r.text()).trim()
  if (!raw) return []

  if (raw[0] === "{") {
    try {
      const data = JSON.parse(raw)
      return (data.events || [])
        .map((e) => ({
          tMs: e.tStartMs || 0,
          text: (e.segs || []).map((s) => s.utf8 || "").join("").replace(/\s+/g, " ").trim(),
        }))
        .filter((c) => c.text)
    } catch {
      /* fall through to XML parsing */
    }
  }
  // XML timedtext, fmt=3: <p t="123" d="..">word<s>..</s></p>
  const pTags = raw.match(/<p\b[^>]*>[\s\S]*?<\/p>/g)
  if (pTags) {
    return pTags
      .map((p) => {
        const t = p.match(/\bt="(\d+)"/)
        return { tMs: t ? parseInt(t[1], 10) : 0, text: clean(p) }
      })
      .filter((c) => c.text)
  }
  // Legacy: <text start="12.3" dur="..">…</text>
  const tTags = raw.match(/<text\b[^>]*>[\s\S]*?<\/text>/g)
  if (tTags) {
    return tTags
      .map((t) => {
        const s = t.match(/\bstart="([\d.]+)"/)
        return { tMs: s ? Math.round(parseFloat(s[1]) * 1000) : 0, text: clean(t) }
      })
      .filter((c) => c.text)
  }
  return []
}

export const cuesToText = (cues) => cues.map((c) => c.text).join(" ").replace(/\s+/g, " ").trim()

// Max characters per chapter when we fall back to size-based splitting. Stays
// under /api/add's 60k lecture cap with margin, so each chapter is summarized
// whole. ~40k chars ≈ 25–35 min of speech.
const CHUNK_CHARS = 40000

function tsToMs(ts) {
  const parts = ts.split(":").map(Number)
  if (parts.some((n) => Number.isNaN(n))) return null
  let s = 0
  for (const p of parts) s = s * 60 + p
  return s * 1000
}

// Parse YouTube-style chapter markers out of the description. YouTube itself
// only shows chapters when the first stamp is 0:00 and there are ≥3 in order —
// we apply the same rule so we don't mistake stray timestamps for chapters.
function parseChapters(description, durationMs) {
  const marks = []
  for (const line of String(description || "").split(/\r?\n/)) {
    const m = line.match(/(?:^|\s|\()(\d{1,2}:\d{2}(?::\d{2})?)\)?\s*[-–—:.]*\s*(\S.*\S|\S)?/)
    if (!m) continue
    const tMs = tsToMs(m[1])
    if (tMs == null) continue
    if (durationMs && tMs > durationMs) continue
    const title = (m[2] || "").replace(/^[-–—:.\s]+/, "").trim()
    marks.push({ tMs, title: title || `${m[1]}` })
  }
  // ascending, deduped by time
  marks.sort((a, b) => a.tMs - b.tMs)
  const uniq = marks.filter((mk, i) => i === 0 || mk.tMs !== marks[i - 1].tMs)
  if (uniq.length >= 3 && uniq[0].tMs <= 5000) return uniq
  return []
}

// Group timed cues into chapters. Uses description chapters when present, else
// splits the transcript into ≤CHUNK_CHARS sequential parts. Returns
// [{ title, startMs, endMs, chars, transcript }].
export function buildChapters(cues, description, durationMs) {
  if (!cues.length) return []
  const endMs = durationMs || (cues[cues.length - 1].tMs + 5000)
  const marks = parseChapters(description, durationMs)

  let base
  if (marks.length) {
    const chapters = marks.map((mk, i) => ({
      title: mk.title,
      startMs: mk.tMs,
      endMs: i + 1 < marks.length ? marks[i + 1].tMs : endMs,
      cues: [],
    }))
    for (const cue of cues) {
      // last chapter whose start ≤ cue time
      let idx = 0
      for (let i = 0; i < chapters.length; i++) if (cue.tMs >= chapters[i].startMs) idx = i
      chapters[idx].cues.push(cue)
    }
    base = chapters
      .map((ch) => ({
        title: ch.title,
        startMs: ch.startMs,
        endMs: ch.endMs,
        transcript: cuesToText(ch.cues),
      }))
      .filter((ch) => ch.transcript)
  } else {
    // No description chapters → size-based parts.
    const parts = []
    let cur = []
    let curLen = 0
    for (const cue of cues) {
      if (curLen && curLen + cue.text.length > CHUNK_CHARS) {
        parts.push(cur)
        cur = []
        curLen = 0
      }
      cur.push(cue)
      curLen += cue.text.length + 1
    }
    if (cur.length) parts.push(cur)
    base = parts.map((p, i) => ({
      title: `Part ${i + 1}`,
      startMs: p[0].tMs,
      endMs: i + 1 < parts.length ? parts[i + 1][0].tMs : endMs,
      transcript: cuesToText(p),
    }))
  }

  // Enforce the per-chapter size cap: any chapter longer than CHUNK_CHARS is
  // split into "(k/n)" sub-parts so /api/add never truncates it.
  const out = []
  for (const ch of base) {
    if (ch.transcript.length <= CHUNK_CHARS) {
      out.push({ ...ch, chars: ch.transcript.length })
      continue
    }
    const pieces = splitText(ch.transcript, CHUNK_CHARS)
    pieces.forEach((piece, k) =>
      out.push({
        title: `${ch.title} (${k + 1}/${pieces.length})`,
        startMs: ch.startMs,
        endMs: ch.endMs,
        transcript: piece,
        chars: piece.length,
      }),
    )
  }
  return out
}

// Split a long string into the fewest ≤max pieces of ROUGHLY EQUAL size, breaking
// at whitespace so words stay whole (avoids a tiny leftover tail chapter).
function splitText(text, max) {
  if (text.length <= max) return [text]
  const n = Math.ceil(text.length / max)
  const target = Math.ceil(text.length / n)
  const pieces = []
  let i = 0
  for (let k = 0; k < n && i < text.length; k++) {
    let end = k === n - 1 ? text.length : Math.min(i + target, text.length)
    if (end < text.length) {
      const sp = text.lastIndexOf(" ", end)
      if (sp > i) end = sp
    }
    pieces.push(text.slice(i, end).trim())
    i = end
  }
  if (i < text.length) pieces.push(text.slice(i).trim()) // boundary drift safety
  return pieces.filter(Boolean)
}
