// Vercel serverless function: take a video link (YouTube) and return its
// transcript so the client can turn it into a study note via /api/add
// (mode:"lecture") — the exact same pipeline the in-site recorder uses after
// stitching its audio segments. No audio download or Whisper needed: we read
// the video's caption track (manual or auto-generated) straight from YouTube.
//
// Why captions instead of downloading+transcribing: Vercel serverless can't run
// yt-dlp and a 1-hour lecture won't fit a single function invocation. Captions
// are just text, so this stays fast and free. Videos with NO captions can't be
// handled here — we return a clear 422 so the UI can explain that.
//
// Required Vercel env vars:
//   ADD_SECRET  — shared password (same one the add-content modal sends)
//
// Runtime: Node (global fetch — Node 18+).

export const config = { maxDuration: 30 }

// Public InnerTube key (the constant every YouTube web client ships with) and
// the mobile client contexts. We ask InnerTube's /player endpoint as the ANDROID
// or IOS app because, since 2024, the caption URLs from the *web* watch page
// return an empty body without a BotGuard "pot" token — the mobile clients still
// serve caption text directly.
const INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"
// Ordered by how well they dodge YouTube's "Sign in to confirm you're not a bot"
// gate from datacenter IPs (Vercel). ANDROID_VR / TVHTML5 / MWEB have historically
// been exempt from the PO-token/bot check; the plain mobile apps come after.
const CLIENTS = [
  {
    name: "ANDROID_VR",
    ua: "com.google.android.apps.youtube.vr.oculus/1.61.48 (Linux; U; Android 12L; eureka-user Build/SQ3A.220605.009.A1) gzip",
    context: {
      clientName: "ANDROID_VR",
      clientVersion: "1.61.48",
      deviceMake: "Oculus",
      deviceModel: "Quest 3",
      androidSdkVersion: 32,
      osName: "Android",
      osVersion: "12L",
      hl: "en",
    },
  },
  {
    name: "TVHTML5",
    ua: "Mozilla/5.0 (ChromiumStylePlatform) Cobalt/Version",
    context: {
      clientName: "TVHTML5_SIMPLY_EMBEDDED_PLAYER",
      clientVersion: "2.0",
      hl: "en",
    },
  },
  {
    name: "MWEB",
    ua: "Mozilla/5.0 (iPhone; CPU iPhone OS 18_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.3 Mobile/15E148 Safari/604.1",
    context: { clientName: "MWEB", clientVersion: "2.20250101.00.00", hl: "en" },
  },
  {
    name: "IOS",
    ua: "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3 like Mac OS X)",
    context: { clientName: "IOS", clientVersion: "20.10.4", hl: "en" },
  },
  {
    name: "ANDROID",
    ua: "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip",
    context: { clientName: "ANDROID", clientVersion: "20.10.38", androidSdkVersion: 30, hl: "en" },
  },
]

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36"

// Pull the 11-char video id out of any common YouTube URL shape.
function videoId(url) {
  try {
    const u = new URL(String(url).trim())
    const host = u.hostname.replace(/^www\./, "")
    if (host === "youtu.be") return u.pathname.slice(1).split("/")[0] || null
    if (host.endsWith("youtube.com")) {
      if (u.searchParams.get("v")) return u.searchParams.get("v")
      const m = u.pathname.match(/\/(?:shorts|embed|live|v)\/([^/?#]+)/)
      if (m) return m[1]
    }
  } catch {
    /* not a URL — fall through to a loose match */
  }
  const m = String(url).match(/[a-zA-Z0-9_-]{11}/)
  return m ? m[0] : null
}

async function playerFor(client, id) {
  const r = await fetch(`https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}`, {
    method: "POST",
    headers: { "Content-Type": "application/json", "User-Agent": client.ua },
    body: JSON.stringify({
      context: { client: client.context },
      videoId: id,
      // Needed by the embedded/TV client to treat the request as an embed.
      ...(client.name === "TVHTML5"
        ? { thirdParty: { embedUrl: "https://www.youtube.com/" } }
        : {}),
    }),
  })
  if (!r.ok) return null
  return r.json().catch(() => null)
}

// Try each client until one both passes the bot gate AND serves non-empty
// caption text. Returns { title, cues, language, autoGenerated, description,
// durationMs } on success, or { error, status } describing why all clients failed.
async function getCaptions(id) {
  let title = ""
  let description = ""
  let durationMs = 0
  let sawBotGate = false
  let sawNoCaptions = false
  let sawUnplayable = ""

  for (const c of CLIENTS) {
    let pr
    try {
      pr = await playerFor(c, id)
    } catch {
      continue
    }
    if (!pr) continue

    if (pr.videoDetails?.title) title = pr.videoDetails.title
    if (pr.videoDetails?.shortDescription) description = pr.videoDetails.shortDescription
    if (pr.videoDetails?.lengthSeconds) durationMs = parseInt(pr.videoDetails.lengthSeconds, 10) * 1000
    const status = pr.playabilityStatus?.status
    const reason = pr.playabilityStatus?.reason || pr.playabilityStatus?.errorScreen || ""

    if (status && status !== "OK") {
      if (/not a bot|sign in|LOGIN_REQUIRED/i.test(status + " " + reason)) sawBotGate = true
      else sawUnplayable = typeof reason === "string" && reason ? reason : status
      continue // this client is blocked — try the next
    }

    const tracks = pr.captions?.playerCaptionsTracklistRenderer?.captionTracks || []
    if (!tracks.length) {
      sawNoCaptions = true
      continue
    }

    const track = pickTrack(tracks)
    let cues = []
    try {
      cues = await fetchCaptionCues(track.baseUrl)
    } catch {
      cues = []
    }
    if (cues.length) {
      return {
        title: title || `YouTube ${id}`,
        cues,
        description,
        durationMs,
        language: track.languageCode || "",
        autoGenerated: track.kind === "asr",
      }
    }
    // tracks present but body empty (datacenter-blocked caption host) → next client
  }

  // Nothing worked — return the most useful reason we saw.
  if (sawNoCaptions && !sawBotGate) {
    return {
      error: "이 영상에는 자막이 없어 노트를 만들 수 없습니다. 자막(자동 생성 포함)이 있는 영상을 사용하세요.",
      status: 422,
    }
  }
  if (sawUnplayable) {
    return { error: `재생할 수 없는 영상입니다: ${sawUnplayable}`, status: 422 }
  }
  if (sawBotGate) {
    return {
      error:
        "YouTube가 서버 요청을 봇으로 차단했습니다 (Sign in to confirm you're not a bot). " +
        "영상 페이지에서 “...더보기 → 스크립트 표시”의 자막을 복사해 ‘노트 작성’ 탭에 붙여넣어 생성해 주세요.",
      status: 502,
    }
  }
  return { error: "영상 정보를 읽지 못했습니다. 잠시 후 다시 시도하세요.", status: 502 }
}

// Prefer a human (non-ASR) track; within that, prefer Korean/English; else take
// whatever exists (the note step translates to English anyway).
function pickTrack(tracks) {
  const score = (t) => {
    let s = 0
    if (t.kind !== "asr") s += 4 // manual captions beat auto-generated
    const lang = (t.languageCode || "").toLowerCase()
    if (lang.startsWith("ko")) s += 2
    else if (lang.startsWith("en")) s += 1
    return s
  }
  return [...tracks].sort((a, b) => score(b) - score(a))[0]
}

function decodeEntities(s) {
  return s
    .replace(/&#39;|&#039;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
}

const clean = (s) => decodeEntities(String(s).replace(/<[^>]+>/g, " ")).replace(/\s+/g, " ").trim()

// Fetch the caption track as TIMED cues [{ tMs, text }] so we can slice it into
// chapters later. Mobile clients return either json3 ({events:[{tStartMs,segs}]})
// or timedtext XML (<p t="ms">…</p> for fmt=3, or <text start="sec">… for legacy).
async function fetchCaptionCues(baseUrl) {
  const url = baseUrl + (baseUrl.includes("?") ? "&" : "?") + "fmt=json3"
  const r = await fetch(url, { headers: { "User-Agent": UA, "Accept-Language": "en" } })
  if (!r.ok) return []
  const raw = (await r.text()).trim()
  if (!raw) return []

  if (raw[0] === "{") {
    try {
      const data = JSON.parse(raw)
      return (data.events || [])
        .map((e) => ({
          tMs: e.tStartMs || 0,
          text: (e.segs || []).map((s) => s.utf8 || "").join("").replace(/\s+/g, " ").trim(),
        }))
        .filter((c) => c.text)
    } catch {
      /* fall through to XML parsing */
    }
  }
  // XML timedtext, fmt=3: <p t="123" d="..">word<s>..</s></p>
  const pTags = raw.match(/<p\b[^>]*>[\s\S]*?<\/p>/g)
  if (pTags) {
    return pTags
      .map((p) => {
        const t = p.match(/\bt="(\d+)"/)
        return { tMs: t ? parseInt(t[1], 10) : 0, text: clean(p) }
      })
      .filter((c) => c.text)
  }
  // Legacy: <text start="12.3" dur="..">…</text>
  const tTags = raw.match(/<text\b[^>]*>[\s\S]*?<\/text>/g)
  if (tTags) {
    return tTags
      .map((t) => {
        const s = t.match(/\bstart="([\d.]+)"/)
        return { tMs: s ? Math.round(parseFloat(s[1]) * 1000) : 0, text: clean(t) }
      })
      .filter((c) => c.text)
  }
  return []
}

const cuesToText = (cues) => cues.map((c) => c.text).join(" ").replace(/\s+/g, " ").trim()

// Max characters per chapter when we fall back to size-based splitting. Stays
// under /api/add's 60k lecture cap with margin, so each chapter is summarized
// whole. ~40k chars ≈ 25–35 min of speech.
const CHUNK_CHARS = 40000

function tsToMs(ts) {
  const parts = ts.split(":").map(Number)
  if (parts.some((n) => Number.isNaN(n))) return null
  let s = 0
  for (const p of parts) s = s * 60 + p
  return s * 1000
}

// Parse YouTube-style chapter markers out of the description. YouTube itself
// only shows chapters when the first stamp is 0:00 and there are ≥3 in order —
// we apply the same rule so we don't mistake stray timestamps for chapters.
function parseChapters(description, durationMs) {
  const marks = []
  for (const line of String(description || "").split(/\r?\n/)) {
    const m = line.match(/(?:^|\s|\()(\d{1,2}:\d{2}(?::\d{2})?)\)?\s*[-–—:.]*\s*(\S.*\S|\S)?/)
    if (!m) continue
    const tMs = tsToMs(m[1])
    if (tMs == null) continue
    if (durationMs && tMs > durationMs) continue
    const title = (m[2] || "").replace(/^[-–—:.\s]+/, "").trim()
    marks.push({ tMs, title: title || `${m[1]}` })
  }
  // ascending, deduped by time
  marks.sort((a, b) => a.tMs - b.tMs)
  const uniq = marks.filter((mk, i) => i === 0 || mk.tMs !== marks[i - 1].tMs)
  if (uniq.length >= 3 && uniq[0].tMs <= 5000) return uniq
  return []
}

// Group timed cues into chapters. Uses description chapters when present, else
// splits the transcript into ≤CHUNK_CHARS sequential parts. Returns
// [{ title, startMs, endMs, chars, transcript }].
function buildChapters(cues, description, durationMs) {
  if (!cues.length) return []
  const endMs = durationMs || (cues[cues.length - 1].tMs + 5000)
  const marks = parseChapters(description, durationMs)

  let base
  if (marks.length) {
    const chapters = marks.map((mk, i) => ({
      title: mk.title,
      startMs: mk.tMs,
      endMs: i + 1 < marks.length ? marks[i + 1].tMs : endMs,
      cues: [],
    }))
    for (const cue of cues) {
      // last chapter whose start ≤ cue time
      let idx = 0
      for (let i = 0; i < chapters.length; i++) if (cue.tMs >= chapters[i].startMs) idx = i
      chapters[idx].cues.push(cue)
    }
    base = chapters
      .map((ch) => ({
        title: ch.title,
        startMs: ch.startMs,
        endMs: ch.endMs,
        transcript: cuesToText(ch.cues),
      }))
      .filter((ch) => ch.transcript)
  } else {
    // No description chapters → size-based parts.
    const parts = []
    let cur = []
    let curLen = 0
    for (const cue of cues) {
      if (curLen && curLen + cue.text.length > CHUNK_CHARS) {
        parts.push(cur)
        cur = []
        curLen = 0
      }
      cur.push(cue)
      curLen += cue.text.length + 1
    }
    if (cur.length) parts.push(cur)
    base = parts.map((p, i) => ({
      title: `Part ${i + 1}`,
      startMs: p[0].tMs,
      endMs: i + 1 < parts.length ? parts[i + 1][0].tMs : endMs,
      transcript: cuesToText(p),
    }))
  }

  // Enforce the per-chapter size cap: any chapter longer than CHUNK_CHARS is
  // split into "(k/n)" sub-parts so /api/add never truncates it.
  const out = []
  for (const ch of base) {
    if (ch.transcript.length <= CHUNK_CHARS) {
      out.push({ ...ch, chars: ch.transcript.length })
      continue
    }
    const pieces = splitText(ch.transcript, CHUNK_CHARS)
    pieces.forEach((piece, k) =>
      out.push({
        title: `${ch.title} (${k + 1}/${pieces.length})`,
        startMs: ch.startMs,
        endMs: ch.endMs,
        transcript: piece,
        chars: piece.length,
      }),
    )
  }
  return out
}

// Split a long string into the fewest ≤max pieces of ROUGHLY EQUAL size, breaking
// at whitespace so words stay whole (avoids a tiny leftover tail chapter).
function splitText(text, max) {
  if (text.length <= max) return [text]
  const n = Math.ceil(text.length / max)
  const target = Math.ceil(text.length / n)
  const pieces = []
  let i = 0
  for (let k = 0; k < n && i < text.length; k++) {
    let end = k === n - 1 ? text.length : Math.min(i + target, text.length)
    if (end < text.length) {
      const sp = text.lastIndexOf(" ", end)
      if (sp > i) end = sp
    }
    pieces.push(text.slice(i, end).trim())
    i = end
  }
  if (i < text.length) pieces.push(text.slice(i).trim()) // boundary drift safety
  return pieces.filter(Boolean)
}

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "POST only" })

  const secret = process.env.ADD_SECRET
  if (!secret) return res.status(500).json({ error: "Server not configured — set ADD_SECRET." })

  let body = req.body
  if (typeof body === "string") {
    try {
      body = JSON.parse(body)
    } catch {
      body = {}
    }
  }
  body = body || {}
  if (body.password !== secret) return res.status(401).json({ error: "Wrong password." })

  const id = videoId(body.url)
  if (!id) {
    return res.status(400).json({ error: "유효한 YouTube 링크가 아닙니다." })
  }

  try {
    const result = await getCaptions(id)
    if (result.error) {
      return res.status(result.status || 502).json({ error: result.error })
    }
    const { title, cues, description, durationMs, language, autoGenerated } = result

    // Chapter mode: return the split so the client can generate one note each.
    if (body.mode === "chapters") {
      const chapters = buildChapters(cues, description, durationMs).map((ch, i) => ({
        index: i,
        title: ch.title,
        startMs: ch.startMs,
        endMs: ch.endMs,
        chars: ch.chars,
        transcript: ch.transcript,
      }))
      return res.status(200).json({
        ok: true,
        videoId: id,
        title,
        language,
        autoGenerated,
        durationMs,
        chaptered: chapters.length > 1,
        chapters,
      })
    }

    // Default: single transcript (client makes one note; add.js caps at 60k).
    const transcript = cuesToText(cues)
    return res.status(200).json({
      ok: true,
      videoId: id,
      title,
      language,
      autoGenerated,
      durationMs,
      length: transcript.length,
      transcript,
    })
  } catch (e) {
    return res.status(500).json({ error: "자막 추출 중 오류: " + (e?.message || "unknown") })
  }
}
