// Vercel serverless function: take a video link (YouTube) and return its
// transcript so the client can turn it into a study note via /api/add
// (mode:"lecture") — the exact same pipeline the in-site recorder uses after
// stitching its audio segments.
//
// The caption extraction itself lives in ./_youtube.js, shared with the local
// CLI (scripts/ingest.mjs). Read the header comment there for why the local
// path exists: YouTube bot-gates datacenter IPs, so this endpoint fails for
// many videos and answers with BOT_GATE_HINT telling you to run the CLI.
//
// Required Vercel env vars:
//   ADD_SECRET  — shared password (same one the add-content modal sends)
//
// Runtime: Node (global fetch — Node 18+).

import { buildChapters, cuesToText, getCaptions, videoId } from "./_youtube.js"

export const config = { maxDuration: 30 }

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "POST only" })

  const secret = process.env.ADD_SECRET
  if (!secret) return res.status(500).json({ error: "Server not configured — set ADD_SECRET." })

  let body = req.body
  if (typeof body === "string") {
    try {
      body = JSON.parse(body)
    } catch {
      body = {}
    }
  }
  body = body || {}
  if (body.password !== secret) return res.status(401).json({ error: "Wrong password." })

  const id = videoId(body.url)
  if (!id) {
    return res.status(400).json({ error: "유효한 YouTube 링크가 아닙니다." })
  }

  try {
    const result = await getCaptions(id)
    if (result.error) {
      return res.status(result.status || 502).json({ error: result.error, botGate: !!result.botGate })
    }
    const { title, cues, description, durationMs, language, autoGenerated } = result

    // Chapter mode: return the split so the client can generate one note each.
    if (body.mode === "chapters") {
      const chapters = buildChapters(cues, description, durationMs).map((ch, i) => ({
        index: i,
        title: ch.title,
        startMs: ch.startMs,
        endMs: ch.endMs,
        chars: ch.chars,
        transcript: ch.transcript,
      }))
      return res.status(200).json({
        ok: true,
        videoId: id,
        title,
        language,
        autoGenerated,
        durationMs,
        chaptered: chapters.length > 1,
        chapters,
      })
    }

    // Default: single transcript (client makes one note; add.js caps at 60k).
    const transcript = cuesToText(cues)
    return res.status(200).json({
      ok: true,
      videoId: id,
      title,
      language,
      autoGenerated,
      durationMs,
      length: transcript.length,
      transcript,
    })
  } catch (e) {
    return res.status(500).json({ error: "자막 추출 중 오류: " + (e?.message || "unknown") })
  }
}
